apiVersion: v1
kind: PersistentVolume
metadata:
  # namespace: bernnardooliveira
  name: project2-pv-bernnardooliveira
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/bernnardooliveira/project2-pv

# persistent volumes are not bounded by namespaces
# it turns out that in the minikube environment, all the volume bindings take place inside the minikube vm