apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bernnardooliveira
  name: project2-pvc-bernnardooliveira
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  #volumeName: project2-pv-bernnardooliveira


