name: Docker API Build

on:
  push:
    paths:
      - 'api/version.txt'
      - 'api/**'
      - 'api.dockerfile'
    branches: ["main"]


jobs:
  updateVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3          

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Changing API version
        run: |
          current_version=$(<api/version.txt)
          new_version=$((current_version + 1))
          echo "$new_version" > api/version.txt
      
      - name: Configure GitActions ID
        run: | 
          git config user.email GIT@ACTIONS.COM
          git config user.name new_yaml_modification

      - name: Push version modification
        run: |
          git add .
          git commit -m 'GITACTIONS: changed API version'
          git push origin main

      - name: Login in Docker
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Building Docker Image
        run: docker build . -f api.dockerfile -t bernnardosbo/backend:ga-${{ github.run_number }}

      - name: Pushing Docker Image
        run: docker push bernnardosbo/backend:ga-${{ github.run_number }}

  updateClientYaml:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitActions ID
        run: | 
          git config user.email GIT@ACTIONS.COM
          git config user.name new_yaml_modification
      
      - name: Pull any yaml changes
        run : |
          git pull

      - name: Modify K8S manifest
        run: sed -i "s+bernnardosbo/backend.*+bernnardosbo/backend:ga-$RUN_NUMBER+g" k8s/config.yaml
        env:
          RUN_NUMBER: ${{ github.run_number }}
          
      - name: Push K8s modification
        run: |
          git add .
          git commit -m 'GITACTIONS: k8s manifest API update (id: ${{ github.run_number }})'
          git push origin main
          






          
